/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyek;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/**
 *
 * @author Winda AU
 */
public class panelIntro extends javax.swing.JPanel {

    MediaPlayer mplayerIntro, mplayerLoad;
    Boolean vidIntroOn;
    Boolean vidLoadOn;
    public panelIntro() {
        initComponents();
        this.setFocusable(true);
//        Media media = new Media("videos/intro.mp4");
//        //Media mediaLoad = new Media("videos/load screen.mp4");
//        mplayerIntro = new MediaPlayer(media);
//        //mplayerLoad = new MediaPlayer(mediaLoad);
//        mplayerIntro.setAutoPlay(true);
        
    }
    
    public void playIntro(){
        mplayerIntro.play();
    }
    
    public void playLoadScreen(){
        mplayerLoad.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            try {
                //            mplayerIntro.stop();
//            this.setVisible(false);
//            LoginFrame lp = new LoginFrame();
//            lp.setLocationRelativeTo(null);
//            lp.setVisible(true);    

            File f = new File("videos/intro.mp4");
            Desktop d = Desktop.getDesktop();
            d.open(f);
            
            } catch (IOException ex) {
                Logger.getLogger(panelIntro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
