package Proyek;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class panelGameIntro extends javax.swing.JPanel {

    Timer t;
    int ctrWaktu;
    Boolean canSkip;
    BufferedImage bgIntro;
    public formIntro f_intro;
    
    public panelGameIntro() {
        try {
            initComponents();
            this.setFocusable(true);
            ctrWaktu = 0;
            canSkip = false;
            lblSkip.setVisible(true);
            try {
                bgIntro = ImageIO.read(new File("images/bgIntro.jpg"));
            } catch (IOException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            File f = new File("videos/intro.mp4");
            Desktop d = Desktop.getDesktop();
            d.open(f);
            
            t = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    if (ctrWaktu >= 3) {
                        canSkip = true;
                        lblSkip.setText("PRESS SPACE TO SKIP THE VIDEO");
                    }
                    else{
                        lblSkip.setText("WELCOME TO SPACE SHOOTER");
                    }
                    
                    checkIntroDone(false);
                    System.out.println("waktu : " + ctrWaktu);
                }
            });
            t.start();
        } catch (IOException ex) {
            Logger.getLogger(panelGameIntro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void showMainMenu(){
        f_intro.setVisible(false);
        LoginFrame login = new LoginFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }
    
    private void checkIntroDone(Boolean skip){
        if (skip) {
            t.stop();
            showMainMenu();
        }
        else{
            if (ctrWaktu >= 10) {
                t.stop();
                showMainMenu();
            } 
            else{
                ctrWaktu++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSkip = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblSkip.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        lblSkip.setForeground(new java.awt.Color(255, 255, 255));
        lblSkip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSkip.setText("WELCOME TO SPACE SHOOTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            if (canSkip) {
                checkIntroDone(true);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.
        
        Graphics2D g2 = (Graphics2D)grphcs;
        g2.drawImage(bgIntro,0,0,550,550,null);
        
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSkip;
    // End of variables declaration//GEN-END:variables
}
